#ifndef __PLANALTA_FILTERING__
#define	__PLANALTA_FILTERING__

#include <xc.h>
#include <adc.h>
#include "filters_planalta.h"

#define PLANALTA_5KHZ_F0_OUTPUT_SIZE      (ADC_BUFFER_LENGTH / PLANALTA_5KHZ_N_ADC_CHANNELS)
#define PLANALTA_5KHZ_F1_INPUT_SIZE       (PLANALTA_5KHZ_F0_OUTPUT_SIZE / 2)
#define PLANALTA_5KHZ_F1_OUTPUT_SIZE      (PLANALTA_5KHZ_F1_INPUT_SIZE / PLANALTA_DEC_FACT_F1)
#define PLANALTA_5KHZ_F2_INPUT_SIZE       (PLANALTA_DEC_FACT_F2)
#define PLANALTA_5KHZ_F2_OUTPUT_SIZE      (PLANALTA_5KHZ_F2_INPUT_SIZE / PLANALTA_DEC_FACT_F2)
#define PLANALTA_5KHZ_F3_INPUT_SIZE       (PLANALTA_DEC_FACT_F3)
#define PLANALTA_5KHZ_F3_OUTPUT_SIZE      (PLANALTA_5KHZ_F3_INPUT_SIZE / PLANALTA_DEC_FACT_F3)
#define PLANALTA_5KHZ_F4_INPUT_SIZE       (PLANALTA_DEC_FACT_F4)
#define PLANALTA_5KHZ_F4_OUTPUT_SIZE      (PLANALTA_5KHZ_F4_INPUT_SIZE / PLANALTA_DEC_FACT_F4)
#define PLANALTA_5KHZ_FX_INPUT_SIZE       (PLANALTA_DEC_FACT_F8)
#define PLANALTA_5KHZ_FX_OUTPUT_SIZE      (PLANALTA_5KHZ_FX_INPUT_SIZE / PLANALTA_DEC_FACT_F8)

#define PLANALTA_10KHZ_F0_OUTPUT_SIZE      (ADC_BUFFER_LENGTH / PLANALTA_10KHZ_N_ADC_CHANNELS)
#define PLANALTA_10KHZ_F1_INPUT_SIZE       (PLANALTA_10KHZ_F0_OUTPUT_SIZE / 2)
#define PLANALTA_10KHZ_F1_OUTPUT_SIZE      (PLANALTA_10KHZ_F0_OUTPUT_SIZE / PLANALTA_DEC_FACT_F1 / 2)
#define PLANALTA_10KHZ_F2_INPUT_SIZE       (PLANALTA_DEC_FACT_F2)
#define PLANALTA_10KHZ_F2_OUTPUT_SIZE      (PLANALTA_10KHZ_F2_INPUT_SIZE / PLANALTA_DEC_FACT_F2)
#define PLANALTA_10KHZ_F3_INPUT_SIZE       (PLANALTA_DEC_FACT_F3)
#define PLANALTA_10KHZ_F3_OUTPUT_SIZE      (PLANALTA_10KHZ_F3_INPUT_SIZE / PLANALTA_DEC_FACT_F3)
#define PLANALTA_10KHZ_F4_INPUT_SIZE       (PLANALTA_DEC_FACT_F4)
#define PLANALTA_10KHZ_F4_OUTPUT_SIZE      (PLANALTA_10KHZ_F4_INPUT_SIZE / PLANALTA_DEC_FACT_F4)
#define PLANALTA_10KHZ_FX_INPUT_SIZE       (PLANALTA_DEC_FACT_F7)
#define PLANALTA_10KHZ_FX_OUTPUT_SIZE      (PLANALTA_10KHZ_FX_INPUT_SIZE / PLANALTA_DEC_FACT_F7)

#define PLANALTA_25KHZ_F0_OUTPUT_SIZE      (ADC_BUFFER_LENGTH / PLANALTA_25KHZ_N_ADC_CHANNELS)
#define PLANALTA_25KHZ_F1_INPUT_SIZE       (PLANALTA_25KHZ_F0_OUTPUT_SIZE / 2)
#define PLANALTA_25KHZ_F1_OUTPUT_SIZE      (PLANALTA_25KHZ_F0_OUTPUT_SIZE / PLANALTA_DEC_FACT_F1 / 2)
#define PLANALTA_25KHZ_F2_INPUT_SIZE       (PLANALTA_DEC_FACT_F2)
#define PLANALTA_25KHZ_F2_OUTPUT_SIZE      (PLANALTA_25KHZ_F2_INPUT_SIZE / PLANALTA_DEC_FACT_F2)
#define PLANALTA_25KHZ_F3_INPUT_SIZE       (PLANALTA_DEC_FACT_F3)
#define PLANALTA_25KHZ_F3_OUTPUT_SIZE      (PLANALTA_25KHZ_F3_INPUT_SIZE / PLANALTA_DEC_FACT_F3)
#define PLANALTA_25KHZ_F4_INPUT_SIZE       (PLANALTA_DEC_FACT_F4)
#define PLANALTA_25KHZ_F4_OUTPUT_SIZE      (PLANALTA_25KHZ_F4_INPUT_SIZE / PLANALTA_DEC_FACT_F4)
#define PLANALTA_25KHZ_FX_INPUT_SIZE       (PLANALTA_DEC_FACT_F6)
#define PLANALTA_25KHZ_FX_OUTPUT_SIZE      (PLANALTA_25KHZ_FX_INPUT_SIZE / PLANALTA_DEC_FACT_F6)

#define PLANALTA_50KHZ_F0_OUTPUT_SIZE      (ADC_BUFFER_LENGTH / PLANALTA_50KHZ_N_ADC_CHANNELS)
#define PLANALTA_50KHZ_F1_INPUT_SIZE       (PLANALTA_50KHZ_F0_OUTPUT_SIZE / 2)
#define PLANALTA_50KHZ_F1_OUTPUT_SIZE      (PLANALTA_50KHZ_F0_OUTPUT_SIZE / PLANALTA_DEC_FACT_F1 / 2)
#define PLANALTA_50KHZ_F2_INPUT_SIZE       (PLANALTA_DEC_FACT_F2)
#define PLANALTA_50KHZ_F2_OUTPUT_SIZE      (PLANALTA_50KHZ_F2_INPUT_SIZE / PLANALTA_DEC_FACT_F2)
#define PLANALTA_50KHZ_F3_INPUT_SIZE       (PLANALTA_DEC_FACT_F3)
#define PLANALTA_50KHZ_F3_OUTPUT_SIZE      (PLANALTA_50KHZ_F3_INPUT_SIZE / PLANALTA_DEC_FACT_F3)
#define PLANALTA_50KHZ_F4_INPUT_SIZE       (PLANALTA_DEC_FACT_F4)
#define PLANALTA_50KHZ_F4_OUTPUT_SIZE      (PLANALTA_50KHZ_F4_INPUT_SIZE / PLANALTA_DEC_FACT_F4)
#define PLANALTA_50KHZ_FX_INPUT_SIZE       (PLANALTA_DEC_FACT_F5)
#define PLANALTA_50KHZ_FX_OUTPUT_SIZE      (PLANALTA_50KHZ_FX_INPUT_SIZE / PLANALTA_DEC_FACT_F5)

#define PLANALTA_COPY_BUFFER_SIZE         (50*PLANALTA_DEC_FACT_F0)
#define PLANALTA_BLOCK1_INPUT_SIZE        (10*PLANALTA_DEC_FACT_F1)
#define PLANALTA_BLOCK2_INPUT_SIZE        (10*PLANALTA_DEC_FACT_F2)
#define PLANALTA_BLOCK3_INPUT_SIZE        (PLANALTA_DEC_FACT_F3)
#define PLANALTA_BLOCK4_INPUT_SIZE        (PLANALTA_DEC_FACT_F4)
#define PLANALTA_BLOCK0_OUTPUT_SIZE       (PLANALTA_COPY_BUFFER_SIZE  / PLANALTA_DEC_FACT_F0)
#define PLANALTA_BLOCK1_OUTPUT_SIZE       (PLANALTA_BLOCK1_INPUT_SIZE / PLANALTA_DEC_FACT_F1)
#define PLANALTA_BLOCK2_OUTPUT_SIZE       (PLANALTA_BLOCK2_INPUT_SIZE / PLANALTA_DEC_FACT_F2)
#define PLANALTA_BLOCK3_OUTPUT_SIZE       (PLANALTA_BLOCK3_INPUT_SIZE / PLANALTA_DEC_FACT_F3)
#define PLANALTA_BLOCK4_OUTPUT_SIZE       (PLANALTA_BLOCK4_INPUT_SIZE / PLANALTA_DEC_FACT_F4)


#ifdef	__cplusplus
extern "C" {
#endif

void adc_rx_callback_50khz(void);
void adc_rx_callback_25khz(void);
void adc_rx_callback_10khz(void);
void adc_rx_callback_5khz(void);

extern uint8_t start_filter2, start_filter3, start_filter4, start_filter5;
void run_filter2_5khz(void);
void run_filter3_5khz(void);
void run_filter4_5khz(void);
void run_filter5_5khz(void);
void run_filter6_5khz(void);

void run_filter2_10khz(void);
void run_filter3_10khz(void);
void run_filter4_10khz(void);
void run_filter5_10khz(void);
void run_filter6_10khz(void);

void run_filter2_25khz(void);
void run_filter3_25khz(void);
void run_filter4_25khz(void);
void run_filter5_25khz(void);
void run_filter6_25khz(void);

void run_filter2_50khz(void);
void run_filter3_50khz(void);
void run_filter4_50khz(void);
void run_filter5_50khz(void);
void run_filter6_50khz(void);

void init_filtering(void);

void planalta_clear_filter_buffers(void);

void planalta_filter_50khz(void);
void planalta_filter_25khz(void);
void planalta_filter_10khz(void);
void planalta_filter_5khz(void);
    
#ifdef	__cplusplus
}
#endif

#endif

